default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local: &local
  <<: *default
  username: <%= ENV['POSTGRES_USER'] %>
  host: <%= ENV['POSTGRES_HOST'] %>


development:
  primary:
    <<: *local
    database: archaeopteryx_development
    migrations_paths: db/primary_migrate
  primary_replica:
    <<: *local
    database: archaeopteryx_development
    replica: true
  form_builder: 
    <<: *local
    database: form_builder_development
    migrations_paths: domains/form_builder/db/migrate
  form_builder_replica:
    <<: *local
    database: form_builder_development
    replica: true

test:
  primary:
    <<: *local
    database: archaeopteryx_test
  primary_replica:
    <<: *local
    database: archaeopteryx_test
    replica: true
  form_builder: 
    <<: *local
    database: form_builder_test
  form_builder_replica:
    <<: *local
    database: form_builder_test
    replica: true

production:
  primary:
    <<: *local
    database: archaeopteryx_production
    migrations_paths: db/primary_migrate
  primary_replica:
    <<: *local
    database: archaeopteryx_production
    replica: true
  form_builder: 
    <<: *local
    database: form_builder_production
    migrations_paths: domains/form_builder/db/migrate
  form_builder_replica:
    <<: *local
    database: form_builder_production
    replica: true

